### ISSUE TITLE
Problem with ipython 2.3

### ISSUE THREAD

**Issue by hooger** [millejoh/emacs-ipython-notebook#106]
Hello!
I am trying to use emacs-ein, but I have problems.
ein:notebooklist-open works properly, I can create, open and delete notebooks, however when I open a notebook it produces some messages in the Warnings tab:

```
Error (websocket): in callback `on-open': Cannot send message to a closed websocket: cl-struct-websocket-frame, text, "{\"header\":{\"msg_id\":\"e6a03e22-4c47-4d25-a037-c7cedd9bb10b\",\"username\":\"username\",\"session\":\"ee7d57c5-847e-49c0-885e-3f7b6b1089c4\",\"msg_type\":\"execute_request\"},\"metadata\":{},\"content\":{\"code\":\"__import__('sys').stdout.write(__import__('os').getcwd())\",\"silent\":true,\"user_variables\":[],\"user_expressions\":{},\"allow_stdin\":true},\"parent_header\":{}}", nil, t
Error (websocket): in callback `on-open': Wrong type argument: arrayp, nil
Error (websocket): in callback `on-close': Wrong type argument: arrayp, nil
```

and the ipython notebook console says:

```
WARNING:tornado.access:404 GET /api/contents (127.0.0.1) 9.40ms referer=None
INFO:tornado.access:302 GET /api/notebooks/ (127.0.0.1) 0.38ms
2016-07-21 17:02:25.757 [NotebookApp] Uploading notebook to /
INFO:tornado.access:302 GET /api/notebooks/ (127.0.0.1) 0.34ms
2016-07-21 17:02:25.841 [NotebookApp] Kernel started: ba7d72bb-c8ff-4249-b230-9569b5b11b7d
2016-07-21 17:02:25.916 [NotebookApp] WARNING | Missing Origin header, rejecting WebSocket connection.
ERROR:tornado.application:Uncaught exception in /api/kernels/ba7d72bb-c8ff-4249-b230-9569b5b11b7d/shell
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/websocket.py", line 316, in wrapper
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/IPython/html/base/zmqhandlers.py", line 147, in open
    raise web.HTTPError(403)
HTTPError: HTTP 403: Forbidden
2016-07-21 17:02:25.920 [NotebookApp] WARNING | Missing Origin header, rejecting WebSocket connection.
ERROR:tornado.application:Uncaught exception in /api/kernels/ba7d72bb-c8ff-4249-b230-9569b5b11b7d/iopub
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/websocket.py", line 316, in wrapper
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/IPython/html/base/zmqhandlers.py", line 147, in open
    raise web.HTTPError(403)
HTTPError: HTTP 403: Forbidden
2016-07-21 17:02:25.931 [NotebookApp] WARNING | Missing Origin header, rejecting WebSocket connection.
ERROR:tornado.application:Uncaught exception in /api/kernels/ba7d72bb-c8ff-4249-b230-9569b5b11b7d/shell
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/websocket.py", line 316, in wrapper
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/IPython/html/base/zmqhandlers.py", line 147, in open
    raise web.HTTPError(403)
HTTPError: HTTP 403: Forbidden
```
System is Debian 8, up-to-date,
emacs version is 24.4.1
ein version is installed through el-get
jupyter is not installed, as it is not in the official repo, ipython is used instead. Version: 2.3.0-2
python-tornado version is: 3.2.2-1.1
What can be the problem?

**Comment by millejoh** [comment]
You need at least Tornado 4.0.2 to run EIN. The requirements in the [documentation](http://millejoh.github.io/emacs-ipython-notebook/#requirements) are mostly update to date.

**Comment by hooger** [comment]
Sorry, I haven't checked that (though I read this document multiple times...). Thank you for the answer!
