### ISSUE TITLE
EIN connection to notebook results in HTTPError: HTTP 403: Forbidden

### ISSUE THREAD

**Issue by Knusper** [millejoh/emacs-ipython-notebook#26]
## Description of the problem you have

EIN does not talk with the server. I can create a notebook from the notebooklist menu, but when I connect to it I get HTTPError: HTTP 403: Forbidden on the shell where I started iPython.

-> ipython notebook --port 9999
2015-02-15 22:53:34.015 [NotebookApp] Using existing profile dir: u'/home/knusper/.ipython/profile_default'
2015-02-15 22:53:34.021 [NotebookApp] Using MathJax from CDN: https://cdn.mathjax.org/mathjax/latest/MathJax.js
2015-02-15 22:53:34.077 [NotebookApp] Serving notebooks from local directory: /home/knusper/python/python-scripts
2015-02-15 22:53:34.078 [NotebookApp] 0 active kernels 
2015-02-15 22:53:34.078 [NotebookApp] The IPython Notebook is running at: http://localhost:9999/
2015-02-15 22:53:34.078 [NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
WARNING:tornado.access:404 GET /api (127.0.0.1) 25.06ms referer=None
INFO:tornado.access:302 GET /api/notebooks/ (127.0.0.1) 0.45ms
2015-02-15 22:53:58.697 [NotebookApp] Kernel started: f69fff92-6707-42c3-a97d-d76b600af907
2015-02-15 22:53:58.765 [NotebookApp] WARNING | Cross Origin WebSocket Attempt from None
ERROR:tornado.application:Uncaught exception in /api/kernels/f69fff92-6707-42c3-a97d-d76b600af907/shell
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/tornado/websocket.py", line 322, in wrapper
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/IPython/html/base/zmqhandlers.py", line 138, in open
    raise web.HTTPError(403)
HTTPError: HTTP 403: Forbidden
2015-02-15 22:53:58.770 [NotebookApp] WARNING | Cross Origin WebSocket Attempt from None
ERROR:tornado.application:Uncaught exception in /api/kernels/f69fff92-6707-42c3-a97d-d76b600af907/iopub
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/tornado/websocket.py", line 322, in wrapper
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/IPython/html/base/zmqhandlers.py", line 138, in open
    raise web.HTTPError(403)
HTTPError: HTTP 403: Forbidden

## Your IPython configuration

ipython 2.2.0

`ipython notebook --port 9999`

`http://localhost:9999/`

## Additional information (if any)

Using the ipython notebook in the webbrowser works fine. 

## System info:

```cl
("EIN system info"
 :emacs-version
 "GNU Emacs 24.3.1 (x86_64-suse-linux-gnu, GTK+ Version 3.14.2)
 of 2014-10-15 on build05"
 :emacs-bzr-version nil
 :window-system x
 :emacs-variant nil
 :os
 (:uname
  "Linux knuspertop.site 3.16.7-7-desktop #1 SMP PREEMPT Wed Dec 17 18:00:44 UTC 2014 (762f27a) x86_64 x86_64 x86_64 GNU/Linux
"
  :lsb-release
  "LSB Version:	n/a
Distributor ID:	openSUSE project
Description:	openSUSE 13.2 (Harlequin) (x86_64)
Release:	13.2
Codename:	Harlequin
")
 :image-types
 (svg imagemagick png gif tiff jpeg xpm xbm pbm postscript)
 :image-types-available
 (svg imagemagick png gif tiff jpeg xpm xbm pbm postscript)
 :request
 (:backend curl)
 :ein
 (:version "0.3"
	   :source-dir "/home/knusper/.emacs.d/elpa/ein-20150215.934/")
 :lib
 ((:name "websocket"
	 :path "~/.emacs.d/elpa/websocket-20141226.1957/websocket.elc"
	 :featurep t
	 :version-var websocket-version
	 :version "1.3")
  (:name "request"
	 :path "~/.emacs.d/elpa/request-20140316.417/request.elc"
	 :featurep t
	 :version-var request-version
	 :version "0.2.0")
  (:name "auto-complete"
	 :path "~/.emacs.d/elpa/auto-complete-20150201.150/auto-complete.elc"
	 :featurep t
	 :version-var nil
	 :version nil)
  (:name "auto-complete"
	 :path "~/.emacs.d/elpa/auto-complete-20150201.150/auto-complete.elc"
	 :featurep t
	 :version-var nil
	 :version nil)
  (:name "popup"
	 :path "~/.emacs.d/elpa/popup-20150116.1223/popup.elc"
	 :featurep t
	 :version-var popup-version
	 :version "0.5.2")
  (:name "python"
	 :path "/usr/share/emacs/24.3/lisp/progmodes/python.elc"
	 :featurep t
	 :version-var nil
	 :version nil)
  (:name "markdown-mode"
	 :path "~/.emacs.d/elpa/markdown-mode-20150121.1229/markdown-mode.elc"
	 :featurep t
	 :version-var markdown-mode-version
	 :version "2.0")))
```

**Comment by millejoh** [comment]
What version of Tornado are you running? There are known issues with versions earlier than 4.0.2, specifically the cross origin websocket error you are seeing.

**Comment by Knusper** [comment]
Uh - I'm on openSUSE and apparently they ship tornado 3.something... I removed the version they shipped and installed the newest tornado via pip. Now everything seems to be fine... Closed!
