### ISSUE TITLE
*anaconda-mode* buffer prints this message constantly: TypeError: __init__() takes from 1 to 2 positional arguments but 5 positional arguments (and 1 keyword-only argument) were given

### ISSUE THREAD

**Issue by maikol-solis** [millejoh/emacs-ipython-notebook#774]
If I start a jupyter notebook using `ein:run` and start to insert cells and type code, this appears constantly in the minibuffer 

`Server error: TypeError('__init__() takes from 1 to 2 positional arguments but 5 positional arguments (and 1 keyword-only argument) were given') - see *anaconda-mode* for more information. `

Checking the `*anaconda-mode*` buffer, this message appears repeatedly

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/maikol/.emacs.d/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.9.egg/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/maikol/.emacs.d/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.9.egg/service_factory/service.py", line 50, in __call__
    result = self.apply(method, args)
  File "/home/maikol/.emacs.d/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.9.egg/service_factory/service.py", line 105, in apply
    server_error(args['id'], error)
  File "/home/maikol/.emacs.d/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.9.egg/service_factory/errors.py", line 91, in server_error
    raise ServiceException(500, dumps(response))
service_factory.exceptions.ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"code": -32000, "message": "Server error", "data": "TypeError(\'__init__() takes from 1 to 2 positional arguments but 5 positional arguments (and 1 keyword-only argument) were given\')"}}')
127.0.0.1 - - [22/Jan/2021 09:57:10] ================================================================================
Traceback (most recent call last):
  File "/home/maikol/.emacs.d/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.9.egg/service_factory/service.py", line 101, in apply
    result = method(**params)
  File "<string>", line 99, in wrapper
TypeError: __init__() takes from 1 to 2 positional arguments but 5 positional arguments (and 1 keyword-only argument) were given
```

**Comment by dickmao** [comment]
EIN knows nothing about anaconda.
