### ISSUE TITLE
ein 20220419: ein:run - 403 POST /login (127.0.0.1): XSRF cookie does not match POST argument

### ISSUE THREAD

**Issue by xgqt** [millejoh/emacs-ipython-notebook#838]
## Problem description

`ein:run` fails to connect.

## Steps to reproduce the problem

Run `ein:run`

## System info:

```lisp
ein:dev-sys-info erred: Wrong type argument: stringp, nil
```

... and from IELM:
```lisp
(EL)> (ein:dev-sys-info)
*** Eval error ***  Wrong type argument: stringp, nil
```

Emacs            : 28.1
IPython          : 8.2.0
ipykernel        : 6.13.0
ipywidgets       : 7.7.0
jupyter_client   : 7.1.2
jupyter_core     : 4.9.2
jupyter_server   : not installed
jupyterlab       : not installed
nbclient         : 0.5.13
nbconvert        : 6.4.5
nbformat         : 5.2.0
notebook         : 6.4.10
qtconsole        : 5.2.2
traitlets        : 5.1.1

####  *request-log*:
```
[debug] request--curl: --silent --location --cookie /home/xy/.config/emacs/request/curl-cookie-jar --cookie-jar /home/xy/.config/emacs/request/curl-cookie-jar --include --write-out \n(:num-redirects %{num_redirects} :url-effective "%{url_effective}") --junk-session-cookies --trace-ascii /tmp/curl-trace --compressed --header User-Agent: Mozilla/5.0 --header X-XSRFTOKEN: 2|b1915552|76598b69d28151294d9da2a20d9dca2b|1651665614 --url http://127.0.0.1:8888/login --data-binary @-
[debug] request--curl-callback: event exited abnormally with code 22

[debug] request--callback: UNPARSED
HTTP/1.1 403 Forbidden
Server: TornadoServer/6.1
Content-Type: text/html
Date: Wed, 04 May 2022 12:03:31 GMT
X-Content-Type-Options: nosniff
Content-Security-Policy: frame-ancestors 'self'; report-uri /api/security/csp-report
Content-Length: 7204
Set-Cookie: _xsrf=2|40ca6810|4211b3f6e57f652b46572f4c4c8af1b2|1651665811; Path=/


(:num-redirects 0 :url-effective "http://127.0.0.1:8888/login")
[error] request--callback: peculiar error
[debug] request--callback: executing error
[debug] request--callback: executing complete
```
#### *ein:log-all*:
```
14:03:26:884: [info] ein:jupyter-server--run: /usr/bin/jupyter notebook --notebook-dir=/home/xy/python/notebooks/ --debug --no-browser @#<buffer notebooks>
14:03:31:091: [debug] Login attempt #0 in response to nil from http://127.0.0.1:8888. @#<buffer notebooks>
14:03:31:135: [error] Login to http://127.0.0.1:8888 failed, error-thrown (error . exited abnormally with code 22 ), raw-header HTTP/1.1 403 Forbidden
Server: TornadoServer/6.1
Content-Type: text/html
Date: Wed, 04 May 2022 12:03:31 GMT
X-Content-Type-Options: nosniff
Content-Security-Policy: frame-ancestors 'self'; report-uri /api/security/csp-report
Content-Length: 7204
Set-Cookie: _xsrf=2|40ca6810|4211b3f6e57f652b46572f4c4c8af1b2|1651665811; Path=/
 @#<buffer notebooks>
14:03:31:139: [debug] ein:notebooklist-login--complete STATUS: nil DATA: nil @#<buffer notebooks>
14:07:15:821: [warn] ein:dev-packages: Cannot open load file: No such file or directory, ein-pkg @#<buffer  *temp*>
```
#### *ein server*:
```
[D 14:03:27.708 NotebookApp] Searching ['/home/xy/python/notebooks', '/home/xy/.config/python/jupyter', '/home/xy/.local/etc/jupyter', '/usr/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 14:03:27.708 NotebookApp] Looking for jupyter_config in /etc/jupyter
[D 14:03:27.708 NotebookApp] Looking for jupyter_config in /usr/local/etc/jupyter
[D 14:03:27.708 NotebookApp] Looking for jupyter_config in /usr/etc/jupyter
[D 14:03:27.708 NotebookApp] Looking for jupyter_config in /home/xy/.local/etc/jupyter
[D 14:03:27.709 NotebookApp] Looking for jupyter_config in /home/xy/.config/python/jupyter
[D 14:03:27.709 NotebookApp] Looking for jupyter_config in /home/xy/python/notebooks
[D 14:03:27.709 NotebookApp] Looking for jupyter_notebook_config in /etc/jupyter
[D 14:03:27.710 NotebookApp] Looking for jupyter_notebook_config in /usr/local/etc/jupyter
[D 14:03:27.710 NotebookApp] Looking for jupyter_notebook_config in /usr/etc/jupyter
[D 14:03:27.710 NotebookApp] Looking for jupyter_notebook_config in /home/xy/.local/etc/jupyter
[D 14:03:27.710 NotebookApp] Looking for jupyter_notebook_config in /home/xy/.config/python/jupyter
[D 14:03:27.710 NotebookApp] Looking for jupyter_notebook_config in /home/xy/python/notebooks
[D 14:03:27.711 NotebookApp] Raising open file limit: soft 1024->4096; hard 4096->4096
[D 14:03:27.715 NotebookApp] Paths used for configuration of jupyter_notebook_config: 
    	/etc/jupyter/jupyter_notebook_config.d/ipyparallel.json
    	/etc/jupyter/jupyter_notebook_config.json
[D 14:03:27.716 NotebookApp] Paths used for configuration of jupyter_notebook_config: 
    	/usr/local/etc/jupyter/jupyter_notebook_config.json
[D 14:03:27.716 NotebookApp] Paths used for configuration of jupyter_notebook_config: 
    	/usr/etc/jupyter/jupyter_notebook_config.json
[D 14:03:27.717 NotebookApp] Paths used for configuration of jupyter_notebook_config: 
    	/home/xy/.local/etc/jupyter/jupyter_notebook_config.json
[D 14:03:27.717 NotebookApp] Paths used for configuration of jupyter_notebook_config: 
    	/home/xy/.config/python/jupyter/jupyter_notebook_config.json
[W 14:03:28.009 NotebookApp] Error loading server extension ipyparallel
    Traceback (most recent call last):
      File "/usr/lib/python3.10/site-packages/notebook/notebookapp.py", line 2030, in init_server_extensions
        func(self)
      File "/usr/lib/python3.10/site-packages/ipyparallel/__init__.py", line 91, in _load_jupyter_server_extension
        from .nbextension.handlers import load_jupyter_server_extension
      File "/usr/lib/python3.10/site-packages/ipyparallel/nbextension/handlers.py", line 7, in <module>
        from jupyter_server.utils import url_path_join as ujoin
    ModuleNotFoundError: No module named 'jupyter_server'
[I 14:03:28.015 NotebookApp] Serving notebooks from local directory: /home/xy/python/notebooks
[I 14:03:28.015 NotebookApp] Jupyter Notebook 6.4.10 is running at:
[I 14:03:28.015 NotebookApp] http://localhost:8888/?token=b37a781f39ab9ad8fbe435805de90e819db97ede1b00e064
[I 14:03:28.015 NotebookApp]  or http://127.0.0.1:8888/?token=b37a781f39ab9ad8fbe435805de90e819db97ede1b00e064
[I 14:03:28.015 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 14:03:28.019 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///home/xy/.local/share/jupyter/runtime/nbserver-68579-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=b37a781f39ab9ad8fbe435805de90e819db97ede1b00e064
     or http://127.0.0.1:8888/?token=b37a781f39ab9ad8fbe435805de90e819db97ede1b00e064
[W 14:03:31.101 NotebookApp] 403 POST /login (127.0.0.1): XSRF cookie does not match POST argument
[D 14:03:31.102 NotebookApp] Using contents: services/contents
[D 14:03:31.103 NotebookApp] Using contents: services/contents
[D 14:03:31.129 NotebookApp] Path base/images/favicon.ico served from /usr/lib/python3.10/site-packages/notebook/static/base/images/favicon.ico
[D 14:03:31.130 NotebookApp] Path components/jquery-ui/themes/smoothness/jquery-ui.min.css served from /usr/lib/python3.10/site-packages/notebook/static/components/jquery-ui/themes/smoothness/jquery-ui.min.css
[D 14:03:31.130 NotebookApp] Path components/jquery-typeahead/dist/jquery.typeahead.min.css served from /usr/lib/python3.10/site-packages/notebook/static/components/jquery-typeahead/dist/jquery.typeahead.min.css
[D 14:03:31.130 NotebookApp] Path style/style.min.css served from /usr/lib/python3.10/site-packages/notebook/static/style/style.min.css
[D 14:03:31.131 NotebookApp] Path components/es6-promise/promise.min.js served from /usr/lib/python3.10/site-packages/notebook/static/components/es6-promise/promise.min.js
[D 14:03:31.131 NotebookApp] Path components/react/react.production.min.js served from /usr/lib/python3.10/site-packages/notebook/static/components/react/react.production.min.js
[D 14:03:31.131 NotebookApp] Path components/react/react-dom.production.min.js served from /usr/lib/python3.10/site-packages/notebook/static/components/react/react-dom.production.min.js
[D 14:03:31.131 NotebookApp] Path components/create-react-class/index.js served from /usr/lib/python3.10/site-packages/notebook/static/components/create-react-class/index.js
[D 14:03:31.131 NotebookApp] Path components/requirejs/require.js served from /usr/lib/python3.10/site-packages/notebook/static/components/requirejs/require.js
[D 14:03:31.132 NotebookApp] Path base/images/logo.png served from /usr/lib/python3.10/site-packages/notebook/static/base/images/logo.png
[W 14:03:31.132 NotebookApp] 403 POST /login (127.0.0.1) 31.630000ms referer=None
```
### *Messages*
```
[...]
ein: [info] ein:jupyter-server--run: /usr/bin/jupyter notebook --notebook-dir=/home/xy/python/notebooks/ --debug --no-browser
[error] request--callback: peculiar error
ein: [error] Login to http://127.0.0.1:8888 failed, error-thrown (error . exited abnormally with code 22 ), raw-header HTTP/1.1 403 Forbidden
Server: TornadoServer/6.1
Content-Type: text/html
Date: Wed, 04 May 2022 12:03:31 GMT
X-Content-Type-Options: nosniff
Content-Security-Policy: frame-ancestors 'self'; report-uri /api/security/csp-report
Content-Length: 7204
Set-Cookie: _xsrf=2|40ca6810|4211b3f6e57f652b46572f4c4c8af1b2|1651665811; Path=/
[...]
```

**Comment by dickmao** [comment]
Web security is such a pain in the ass.  Then again, if all we want to do is run analyses, one wonders why bring on jupyter and all its web 2.0 baggage.

`ein:query-prepare-header` sees 2|b1915552|76598b69d28151294d9da2a20d9dca2b|1651665614, but your server expects 2|40ca6810|4211b3f6e57f652b46572f4c4c8af1b2|1651665811.

Upon login, the `request.el` library is supposed to reset the `_xsrf` entry for `HttpOnly_127.0.0.1` in `/home/xy/.config/emacs/request/curl-cookie-jar`, but it's a delicate dance.  In commit 6694467 I seem to have encountered something similar, but I've long forgotten the details.

**Comment by psteinb** [comment]
I have a similar problem. I can trigger it by restarting a kernel. 

Checking my system, orphaned python processes stay alive even after a kernel is restarted.
