### ISSUE TITLE
Invalid JSON saving SymPy pretty printer output

### ISSUE THREAD

**Issue by millejoh** [millejoh/emacs-ipython-notebook#97]
Jupyter generates the following error:

```
[E 19:21:40.653 NotebookApp] Couldn't parse JSON
    Traceback (most recent call last):
      File "C:\Users\millejoh\Anaconda3\lib\site-packages\notebook\base\handlers.py", line 328, in get_json_body
        model = json.loads(body)
      File "C:\Users\millejoh\Anaconda3\lib\json\__init__.py", line 319, in loads
        return _default_decoder.decode(s)
      File "C:\Users\millejoh\Anaconda3\lib\json\decoder.py", line 339, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "C:\Users\millejoh\Anaconda3\lib\json\decoder.py", line 355, in raw_decode
        obj, end = self.scan_once(s, idx)
    json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 78453 (char 78452)
[W 19:21:40.669 NotebookApp] Invalid JSON in body of request
[W 19:21:40.669 NotebookApp] 400 PUT /api/contents/emacs-ipython-notebook/Demo.ipynb (127.0.0.1) 31.21ms referer=None
```

When trying to save output generated from following code:

```
from sympy.interactive import printing
printing.init_printing()

import sympy as sym
from sympy import *
x, y, z = symbols("x y z")

Rational(3,2)*pi + exp(I*x) / (x**2 + y)
```

**Comment by millejoh** [comment]
Somehow, somewhere, this fixed itself along the way.
